/**
 * Landing Page Constants
 *
 * Data for features, testimonials, and other sections
 */

import { Sparkles, Map, DollarSign } from "lucide-react";

export const HERO_IMAGE =
  "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1920&q=80";

export const FEATURES = [
  {
    icon: Sparkles,
    title: "AI-Powered Planning",
    description:
      "Get personalized itineraries generated by AI based on your preferences, travel style, and budget.",
  },
  {
    icon: Map,
    title: "Interactive Maps",
    description:
      "Visualize your journey with Mapbox integration, route optimization, and POI discovery.",
  },
  {
    icon: DollarSign,
    title: "Smart Budgeting",
    description:
      "Track expenses, set limits, and get cost recommendations in real-time.",
  },
];

export const STEPS = [
  {
    step: 1,
    title: "Sign up",
    description: "Create your free account and set your travel preferences",
  },
  {
    step: 2,
    title: "Plan with AI",
    description: "Chat with our AI to generate personalized itineraries",
  },
  {
    step: 3,
    title: "Customize",
    description: "Fine-tune routes, add POIs, and manage your budget",
  },
  {
    step: 4,
    title: "Travel",
    description: "Export or share your perfect travel plan",
  },
];

export const TESTIMONIALS = [
  {
    name: "Sarah Chen",
    role: "Digital Nomad",
    avatar: "SC",
    content:
      "This app completely transformed how I plan my trips. The AI suggestions are incredibly accurate and save me hours of research.",
    rating: 5,
  },
  {
    name: "Marcus Williams",
    role: "Family Traveler",
    avatar: "MW",
    content:
      "Planning family vacations used to be stressful. Now I just tell the AI what we need and it handles everything perfectly.",
    rating: 5,
  },
  {
    name: "Emma Rodriguez",
    role: "Adventure Seeker",
    avatar: "ER",
    content:
      "The budget tracking feature alone is worth it. I've saved hundreds by having real-time spending insights.",
    rating: 5,
  },
];

export const DESTINATION_CARDS = [
  {
    city: "Paris",
    country: "France",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=300",
    delay: 0,
  },
  {
    city: "Tokyo",
    country: "Japan",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=300",
    delay: 1,
  },
  {
    city: "New York",
    country: "USA",
    image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=300",
    delay: 2,
  },
];
